### ISSUE TITLE
UI and UX list of fixes

### ISSUE THREAD

**Issue by varunkumarmedam** [loserscorp/tree#7]
- Tree Title

- Add Family Content Improvement

- Add Session Props for MetaData ( API )

- AddForm Required fields separator

- Min width for Member Data view && Remove Add Description

- Show edit member title in Add Member Form during editing

- Tick mark position change in Add Member form

- Delete content improvement

- Circle Around Mates decrease

- Add Member Clicking Male/Female

- Add Member is Died to is Alive

**Comment by saijayaprakash** [comment]
https://github.com/loserscorp/tree/pull/8

**Comment by saijayaprakash** [comment]
https://github.com/loserscorp/tree/pull/8
